### Get stock details
GET http://localhost:4004/odata/v4/stockssrv/stockset HTTP/1.1

### Post
POST http://localhost:4004/odata/v4/stockssrv/stockset HTTP/1.1
Content-Type: application/json

{

    "symbol": "SBIN",
    "name": "Kotak Bank",
    "quantity": 10,
    "mktprice": 500,
    "avgprice": 200
}

### delete stock
DELETE http://localhost:4004/odata/v4/stockssrv/stockset/0f91cec1-f0e9-4edb-9bbf-aea24871d0b5 HTTP/1.1

### Get portfolio details
GET http://localhost:4004/odata/v4/stockssrv/holdings HTTP/1.1
